[package]
name = "rus-lavi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
num_cpus = "1.13"
linya = "0.2"
itertools = "0.10"
libc = "0.2"
parking_lot = "0.8"
